name: WakaTime status update

on:
  workflow_dispatch:         # <-- Enables manual runs
  schedule:
    - cron: "1 0 * * *"       # Still runs automatically daily at 00:01 UTC

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BRANCH: "main"
          COMMIT_MSG: "Automated Coding Activity Update :alien:"
          STATS_RANGE: "all_time"
